### ISSUE TITLE
HydroBase - change to disabled by default for installer

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-tstool-main#226]
As of TSTool 14.4.0, HydroBase is still enabled by default in the installer. However, most TSTool users probably don't use direct connections to the HydroBase database, especially because web services are available.  However, by default, TSTool will prompt for HydroBase and users have to disable it.  Depending on the person, this can be a challenge.

My suggestion is to change the default for the installer so that HydroBase is disabled by default.  Then power-users that use HydroBase will need to enable it.  This will simplify installation and configuration for the majority of the users.

Documentation will need to be updated accordingly.

**Comment by smalers** [comment]
Feedback from Brian Macpherson at the State is that this would negatively impact HydroBase users so keep it the same.

I suggested that maybe during installation more could be done to help disable HydroBase, such as giving the user the option to disable HydroBase when installing TSTool.

I did update the troubleshooting documentation to discuss how to disable HydroBase features in TSTool if it is not available.

Keep this open for now because the issue does come up frequently for people that use TSTool without HydroBase.

**Comment by smalers** [comment]
How about this as a compromise...

If the user presses ***Cancel*** to cancel the HydroBase login, show an additional dialog message explaining how to disable HydroBase in the configuration files.  This is a common enough issue that a little extra guidance would probably help a lot of people.

**Comment by macphersonbr** [comment]
That seems like a good idea. I'd still like the default to be for HydroBase
to be enabled, but additional dialog is good.

*Brian Macpherson, P.E. *
*Decision Support System Specialist*

C 720-379-0091 <303-866-3441>
1313 Sherman St., Room 718, Denver, CO 80203
***@***.*** ***@***.***>* |
*cwcb.colorado.gov
<http://cwcb.colorado.gov>*
<https://www.facebook.com/coloradowaterconservationboard/>
<https://twitter.com/CWCB_DNR>
<https://www.instagram.com/cowaterconservationboard/>
<https://www.linkedin.com/company/colorado-water-conservation-board/>
* <http://cwcb.state.co.us/>*

**Comment by smalers** [comment]
I added the dialog explaining how to disable HydroBase if "cancel" is used when selecting HydroBase.  I am going to close this issue.
