### ISSUE TITLE
CDSS web services return error

### ISSUE THREAD

**Issue by LisaCBrown** [OpenCDSS/cdss-app-tstool-main#58]
### CDSS web services return error ###
 
Hi Steve, I downloaded the TSTool 12.06 from the CDSS staging website. I clicked on "Commands" --> ReadColoradoHydroBaseRest() and am getting the following warning:
"Unexpected error editing command - refer to log and report to software support"

I checked that I had the datastore enabled under "Tools" --> "Options" and the box is checked, so I am not sure what is going wrong. Also, I think it used to be called HydroBase Guest, but it is not showing up in the list of Datastores in the upper left window (all I have is the RCC-ACIS). I navigated to the TSTool install folder and this is what is in my ColoradoHydroBaseRest.cfg file (I didn't make any changes from the download):

Enabled = True
Type = "ColoradoHydroBaseRestDataStore"
Name = "ColoradoHydroBaseRest"
Description = "Colorado HydroBase REST web Service"
ServiceRootURI = "https://dnrweb.state.co.us/DWR/DwrApiService/api/v2"
ApiKey = ""
ServiceApiDocumentationUri = "https://dnrweb.state.co.us/DWR/DwrApiService/Help"

Also, I tried to enable the ColoradoSMS service, but got an error when I opened TSTool that it was being disabled. Any suggestions?

Thanks!
Lisa

### Environment ###

TSTool version 12.06.00
Operating system version Windows 10 Pro, 64 bit

**Comment by smalers** [comment]
The State's web services were added and worked OK when 12.06.00 was released.  However, there seem to be some configuration issues that cause problems.  I am looking at this now and will be making a 13.00.00dev release on OpenCDSS, which will be the first release integrated with cdss.state.co.us.  This release also has a couple of fixes for other issues so people can provide feedback on those fixes.

**Comment by LisaCBrown** [comment]
Thanks for the update!

**Comment by smalers** [comment]
JR emailed this week that the State has finished some changes and they changed the URL to the web services.  I reviewed all the functionality and things are working.  I'll put out a release once I verify the automated tests and I'm also cleaning up the datastore configuration now that web services have settled in.  I'll put out a 13.x release in a week or so.

**Comment by smalers** [comment]
I provided Lisa with access to TSTool 13.00.00dev, which has been significantly updated to interface with new web services, and the older nonworking web services have been disabled.  There are still some issues with monthly and annual diversion records but daily diversion records work well, including water classes.  I'll see what feedback Lisa provides.

**Comment by LisaCBrown** [comment]
Updated version of TSTool has fixed the issue. Thanks Steve!
